In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

import csv

from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import train_test_split

from sklearn.metrics import precision_recall_fscore_support

from sklearn.metrics import classification_report

from sklearn.model_selection import cross_validate

from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import cross_validate

from sklearn import svm

from sklearn.pipeline import Pipeline

from sklearn.model_selection import GridSearchCV


from sklearn.preprocessing import MultiLabelBinarizer

import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.svm import LinearSVC

from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.model_selection import train_test_split

from sklearn.multiclass import OneVsRestClassifier

from sklearn.metrics import classification_report

from sklearn.metrics import classification_report


In [3]:
#TF-IDF Matrix
with open('C:/Users/rajpu/Desktop/Web analytics Final/Data/final_data_News_Stock_quotes.csv', 'r') as f:
    data = [tuple(line) for line in csv.reader(f)]
    
Lable,Date,News,Company,Sentiment,Open,High,Low,Close,Volume=zip(*data)

date=list(Date)
news=list(News)
sent=list(Sentiment)
lab=list(Lable)

tfidf_vect = TfidfVectorizer() 
tfidf_vect = TfidfVectorizer(stop_words="english") 

dtm= tfidf_vect.fit_transform(news)

print("type of dtm:", type(dtm))
print("size of tfidf matrix:", dtm.shape)

type of dtm: <class 'scipy.sparse.csr.csr_matrix'>
size of tfidf matrix: (237, 12686)


In [4]:
print("type of vocabulary:", type(tfidf_vect.vocabulary_))
print("index of word 'city' in vocabulary:", \
      tfidf_vect.vocabulary_['city'])
voc_lookup={tfidf_vect.vocabulary_[word]:word \
            for word in tfidf_vect.vocabulary_}
print("total number of words:", len(voc_lookup ))

print("\nOriginal text: \n"+news[1])

print("\ntfidf weights: \n")
doc0=dtm[0].toarray()[0]
print(doc0.shape)


top_words=(doc0.argsort())[::-1][0:20]
print([(voc_lookup[i], doc0[i]) for i in top_words])


type of vocabulary: <class 'dict'>
index of word 'city' in vocabulary: 2468
total number of words: 12686

Original text: 
Advertisement 

 Eduardo Porter
 
 
ECONOMIC SCENE
MARCH 6, 2018
 Should Facebook pay us for our puppy pictures? Of course, the idea sounds crazy. Posting puppies on Facebook is not a chore. We love it: Facebook’s 1.4 billion daily users spend the better part of an hour on it every day. It’s amazing that we don’t have to pay for it. And yet the idea is gaining momentum in Silicon Valley and beyond: Facebook and the other technological Goliaths offering free online services — from which they harvest data from and about their users — should pay for every nugget of information they reap. The spring break pictures on Instagram, the YouTube video explaining Minecraft tactics, the internet searches and the Amazon purchases, even your speed following Waze on the way to spend Thanksgiving with your in-laws — this data is valuable. It will become more valuable, potentially m

In [5]:
X_train, X_test, y_train, y_test = train_test_split(\
                dtm, sent, test_size=0.3, random_state=0)
# train a multinomial naive Bayes model using the testing data
clf = MultinomialNB().fit(X_train, y_train)

predicted=clf.predict(X_test)

labels=sorted(list(set(sent)))

precision, recall, fscore, support=\
     precision_recall_fscore_support(\
     y_test, predicted, labels=labels)
    
#print(precision)
#print(recall)
#print(fscore)
#print(support)

print(classification_report(y_test, predicted, target_names=labels))





             precision    recall  f1-score   support

          1       0.86      0.84      0.85        43
          2       0.77      0.79      0.78        29

avg / total       0.82      0.82      0.82        72



C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 2, does not match size of target_names, 3
  .format(len(labels), len(target_names))


In [6]:
metrics = ['precision_macro', 'recall_macro', "f1_macro"]

clf = MultinomialNB()
#clf = MultinomialNB(alpha=0.8)

cv = cross_validate(clf, dtm, sent, scoring=metrics, cv=5)
print("Test data set average precision:")
print(cv['test_precision_macro'])
print("\nTest data set average recall:")
print(cv['test_recall_macro'])
print("\nTest data set average fscore:")
print(cv['test_f1_macro'])

# To see the performance of training data set use 
#cv['train_xx_macro']
print("\n Train data set average fscore:")
print(cv['train_f1_macro'])

Test data set average precision:
[ 0.53809524  0.82894737  0.78571429  0.77708333  0.79166667]

Test data set average recall:
[ 0.5084058   0.7173913   0.60869565  0.74094203  0.77840909]

Test data set average fscore:
[ 0.5009009   0.6998557   0.54220779  0.73496241  0.77884615]

 Train data set average fscore:
[ 0.93028099  0.62586422  0.63673683  0.64026144  0.615519  ]


C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajp

In [7]:
#SVM model

metrics = ['precision_macro', 'recall_macro', "f1_macro"]

# initiate an linear SVM model
clf = svm.LinearSVC()

cv = cross_validate(clf, dtm, sent, scoring=metrics, cv=5)
print("Test data set average precision:")
print(cv['test_precision_macro'])
print("\nTest data set average recall:")
print(cv['test_recall_macro'])
print("\nTest data set average fscore:")
print(cv['test_f1_macro'])


Test data set average precision:
[ 0.57166667  0.77097902  0.74456522  0.82358871  0.87884615]

Test data set average recall:
[ 0.58434783  0.76956522  0.74456522  0.79076087  0.87310606]

Test data set average fscore:
[ 0.57738095  0.76993464  0.74456522  0.78240741  0.86931818]


C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(\
                dtm, sent, test_size=0.3, random_state=0)
# train a multinomial naive Bayes model using the testing data
#clf = MultinomialNB().fit(X_train, y_train)
clf = svm.LinearSVC().fit(X_train, y_train)
predicted=clf.predict(X_test)

labels=sorted(list(set(sent)))

precision, recall, fscore, support=\
     precision_recall_fscore_support(\
     y_test, predicted, labels=labels)
    
#print(precision)
#print(recall)
#print(fscore)
#print(support)

print(classification_report(y_test, predicted, target_names=labels))





             precision    recall  f1-score   support

          1       0.87      0.79      0.83        43
          2       0.73      0.83      0.77        29

avg / total       0.81      0.81      0.81        72



C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 2, does not match size of target_names, 3
  .format(len(labels), len(target_names))
