In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

import csv

from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import train_test_split

from sklearn.metrics import precision_recall_fscore_support

from sklearn.metrics import classification_report

from sklearn.model_selection import cross_validate

from sklearn.naive_bayes import MultinomialNB

from sklearn.model_selection import cross_validate

from sklearn import svm

from sklearn.pipeline import Pipeline

from sklearn.model_selection import GridSearchCV


from sklearn.preprocessing import MultiLabelBinarizer

import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.svm import LinearSVC

from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.model_selection import train_test_split

from sklearn.multiclass import OneVsRestClassifier

from sklearn.metrics import classification_report

from sklearn.metrics import classification_report


In [3]:
#TF-IDF Matrix
with open('C:/Users/rajpu/Desktop/Web analytics Final/Python Code/Updated_Files/Updated Wall_Street.csv', 'r') as f:
    data = [tuple(line) for line in csv.reader(f)]
    
Title,entryDate,Label,Articles=zip(*data)

#date=list(Date)
news=list(Articles)
sent=list(Label)
#lab=list(Lable)

tfidf_vect = TfidfVectorizer() 
tfidf_vect = TfidfVectorizer(stop_words="english") 

dtm= tfidf_vect.fit_transform(news)

print("type of dtm:", type(dtm))
print("size of tfidf matrix:", dtm.shape)

type of dtm: <class 'scipy.sparse.csr.csr_matrix'>
size of tfidf matrix: (257, 8846)


In [4]:
print("type of vocabulary:", type(tfidf_vect.vocabulary_))
print("index of word 'city' in vocabulary:", \
      tfidf_vect.vocabulary_['city'])
voc_lookup={tfidf_vect.vocabulary_[word]:word \
            for word in tfidf_vect.vocabulary_}
print("total number of words:", len(voc_lookup ))

print("\nOriginal text: \n"+news[1])

print("\ntfidf weights: \n")
doc0=dtm[0].toarray()[0]
print(doc0.shape)


top_words=(doc0.argsort())[::-1][0:20]
print([(voc_lookup[i], doc0[i]) for i in top_words])


type of vocabulary: <class 'dict'>
index of word 'city' in vocabulary: 1653
total number of words: 8846

Original text: 
Wells Fargo & Co.'s board stripped eight top executives of 2016 cash bonuses and clawed back certain stock awards in response to the bank's sales-practices scandal.The San Francisco-based lender said Wednesday that the compensation cuts for current executives don't reflect the culpability of individuals but are meant to show their accountability for the bank's overall performance and reputational risk as a result of the scandal.Eight of Wells Fargo's executives, including current Chief Executive Officer Timothy Sloan and financial chief John Shrewsberry, are affected by the moves, resulting in a loss of total compensation of about $32 million.Mr. Sloan didn't become chief executive until October when former CEO John Stumpf abruptly retired following congressional grillings and a public uproar over the sales-practices scandal that also cost the bank a $185 million set

In [11]:
X_train, X_test, y_train, y_test = train_test_split(\
                dtm, sent, test_size=0.3, random_state=0)
# train a multinomial naive Bayes model using the testing data
clf = MultinomialNB().fit(X_train, y_train)

predicted=clf.predict(X_test)

labels=sorted(list(set(sent)))

precision, recall, fscore, support=\
     precision_recall_fscore_support(\
     y_test, predicted, labels=labels)
    
#print(precision)
#print(recall)
#print(fscore)
#print(support)

print(classification_report(y_test, predicted, target_names=labels))





             precision    recall  f1-score   support

                  0.00      0.00      0.00         4
          0       0.71      0.19      0.29        27
          1       0.63      0.96      0.76        47

avg / total       0.63      0.64      0.56        78



C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 3, does not match size of target_names, 4
  .format(len(labels), len(target_names))


In [12]:
metrics = ['precision_macro', 'recall_macro', "f1_macro"]

clf = MultinomialNB()
#clf = MultinomialNB(alpha=0.8)

cv = cross_validate(clf, dtm, sent, scoring=metrics, cv=5)
print("Test data set average precision:")
print(cv['test_precision_macro'])
print("\nTest data set average recall:")
print(cv['test_recall_macro'])
print("\nTest data set average fscore:")
print(cv['test_f1_macro'])

# To see the performance of training data set use 
#cv['train_xx_macro']
print("\n Train data set average fscore:")
print(cv['train_f1_macro'])

Test data set average precision:
[ 0.22333333  0.52941176  0.41950113  0.53741497  0.45740741]

Test data set average recall:
[ 0.24722222  0.35185185  0.35925926  0.37037037  0.38066261]

Test data set average fscore:
[ 0.19880952  0.2820013   0.3082178   0.31983122  0.34749035]

 Train data set average fscore:
[ 0.5087386   0.36586979  0.34761905  0.33301727  0.36445899]


C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajp

In [13]:
#SVM model

metrics = ['precision_macro', 'recall_macro', "f1_macro"]

# initiate an linear SVM model
clf = svm.LinearSVC()

cv = cross_validate(clf, dtm, sent, scoring=metrics, cv=5)
print("Test data set average precision:")
print(cv['test_precision_macro'])
print("\nTest data set average recall:")
print(cv['test_recall_macro'])
print("\nTest data set average fscore:")
print(cv['test_f1_macro'])


Test data set average precision:
[ 0.51932773  0.74332172  0.7254902   0.85416667  0.66011396]

Test data set average recall:
[ 0.56111111  0.70740741  0.71851852  0.84444444  0.77890467]

Test data set average fscore:
[ 0.53472222  0.69352113  0.71875     0.84819734  0.70194805]


C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
X_train, X_test, y_train, y_test = train_test_split(\
                dtm, sent, test_size=0.3, random_state=0)
# train a multinomial naive Bayes model using the testing data
#clf = MultinomialNB().fit(X_train, y_train)
clf = svm.LinearSVC().fit(X_train, y_train)
predicted=clf.predict(X_test)

labels=sorted(list(set(sent)))

precision, recall, fscore, support=\
     precision_recall_fscore_support(\
     y_test, predicted, labels=labels)
    
#print(precision)
#print(recall)
#print(fscore)
#print(support)

print(classification_report(y_test, predicted, target_names=labels))





             precision    recall  f1-score   support

                  0.80      1.00      0.89         4
          0       0.43      0.33      0.38        27
          1       0.65      0.72      0.69        47

avg / total       0.58      0.60      0.59        78



C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\rajpu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1428: UserWarning: labels size, 3, does not match size of target_names, 4
  .format(len(labels), len(target_names))
