In [1]:
import numpy as np
import pandas as pd
import csv

def analyze_tf(arr): 
    
    tf_idf=None
    
    a1=np.sum(arr,axis=1) 
    tf= np.divide(arr.T,a1)     
    a2=np.where(tf.T>0,1,0)
    df=np.sum(a2,axis=0) 
    tf_idf=tf.T/df     
    f=np.argsort(tf_idf)
    print(f[:,-3:]) 
    return tf_idf

def analyze_cars():
    
    ReadFile=pd.read_csv('cars.csv')
    
    df=ReadFile.sort_values(by=['cylinders','mpg'],ascending=False) 
    tf=df.head(3) 
    print(tf)
    
    df['brand']=df.apply(lambda row:row["car"].split(' ')[0], axis=1) 
    
    tf=df[df.brand.isin(['ford','buick','honda'])].groupby(["cylinders","brand"]) 
    tf1=tf['acceleration'].agg([np.mean, np.min, np.max])
    print(tf1)
    
    idf=pd.crosstab(index=df.brand,columns=df.cylinders, values=df.mpg,aggfunc=np.mean)
    print(idf)
    

if __name__ == "__main__":  
    
    #1 Test Question 1
    arr=np.random.randint(0,3,(4,8))

    tf_idf=analyze_tf(arr)
    
   # Test Question 2
    analyze_cars()

[[6 2 0]
 [3 4 5]
 [6 0 7]
 [5 6 4]]
      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
164  20.0          8           262        110    3221          13.5     75   
0    18.0          8           307        130    3504          12.0     70   
2    18.0          8           318        150    3436          11.0     70   

     origin                        car  
164       1        chevrolet monza 2+2  
0         1  chevrolet chevelle malibu  
2         1         plymouth satellite  
                      mean  amin  amax
cylinders brand                       
4         ford   17.250000  16.0  19.0
          honda  16.250000  15.0  17.5
6         buick  18.000000  15.0  21.0
          ford   16.387500  14.5  19.5
8         buick  12.250000  10.0  14.5
          ford   13.153333  10.0  16.0
cylinders      3          4          6          8
brand                                            
amc          NaN        NaN  18.576923  14.937500
audi         NaN  24.000